# Generated by Django 4.2.1 on 2023-05-28 08:01

from django.db import migrations, models
import poll.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('merkle_hash', models.CharField(blank=True, max_length=64)),
                ('self_hash', models.CharField(blank=True, max_length=64)),
                ('nonce', models.IntegerField(null=True)),
                ('timestamp', models.FloatField(default=poll.models.get_time)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidateID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('party', models.CharField(max_length=100)),
                ('criminalRecords', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('vote', models.IntegerField(default=0)),
                ('timestamp', models.FloatField(default=poll.models.get_time)),
                ('block_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteAuth',
            fields=[
                ('username', models.CharField(default='admin', max_length=30, primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('resultCalculated', models.BooleanField(default=False)),
                ('prev_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('public_key_n', models.CharField(max_length=320)),
                ('public_key_e', models.IntegerField(default=0)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoterList',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ph_country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VoterPvt',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=100)),
                ('private_key_n', models.CharField(max_length=320)),
                ('private_key_d', models.CharField(max_length=320)),
            ],
        ),
    ]
